# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LuksoCli < Formula
  desc ""
  homepage "https://github.com/lukso-network/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.1/lukso-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "88062bcb605cb084a7b4e7afa4a61bdf3f55521c69ccc23e45221a6a40b39090"

      def install
        bin.install "lukso-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.1/lukso-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "8b187a7077674fe09d4b1c2790dd6ea84e02486182659c7af7919e6ab7f4b512"

      def install
        bin.install "lukso-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.1/lukso-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "938c29cdbcee68fb78f75fb1e4b113229a91839c44638d7a0555b0386474daea"

      def install
        bin.install "lukso-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukso-network/lukso-cli/releases/download/v0.0.1/lukso-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "092d4ca5ffd7c18135b6d270f837fe00a33944e312c46779747aeacaf68cd948"

      def install
        bin.install "lukso-cli"
      end
    end
  end
end
