# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LuksoCli < Formula
  desc ""
  homepage "https://github.com/meta-bot/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lukso-network/lukso-cli/releases/download/0.0.1/lukso-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "278e656e444b9743307a67fdd0e7e2b33b4e3c21f2fcbca9aff81f1bd4058b46"

      def install
        bin.install "lukso-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lukso-network/lukso-cli/releases/download/0.0.1/lukso-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "f982fef423a9ab3dc8203cf64976672d4d65d9767dbffa61a4411f4730a4e387"

      def install
        bin.install "lukso-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lukso-network/lukso-cli/releases/download/0.0.1/lukso-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "33a52d76ae2acae8802c7c504a4bd75963aa7089bd516db3afc026ee8904ff23"

      def install
        bin.install "lukso-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukso-network/lukso-cli/releases/download/0.0.1/lukso-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "93d480dd2e0764a54e75bf31b0e3bfc10e10d3997571fdfb7e05d2ccaf7b9375"

      def install
        bin.install "lukso-cli"
      end
    end
  end
end
